server {
    listen 80;
    absolute_redirect off;
    root /var/www/public;
    index index.php;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # Si on accède à la racine, on redirige vers /Laurelin/
    location / {
        return 301 $scheme://$http_host/Laurelin/;
    }

    # Rediriger ou servir pictures/ depuis images/ (correctif rapide pour JS compilé)
    location /Laurelin/pictures/ {
        alias /var/www/public/images/;
    }

    # Pour tout ce qui commence par /Laurelin/
    location /Laurelin/ {
        # On tente de servir le fichier physique sans le préfixe /Laurelin/
        rewrite ^/Laurelin/(.*)$ /$1 break;
        
        # On essaie d'abord de servir le fichier ($uri après rewrite).
        try_files $uri /index.php?$query_string;
    }

    # Traitement des fichiers PHP
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
    }
}
