server {
    listen 80;
    absolute_redirect off;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;

    # Si on accède à la racine, on redirige vers /Laurelin/
    location / {
        return 301 $scheme://$http_host/Laurelin/;
    }

    # Pour tout ce qui commence par /Laurelin/
    location /Laurelin/ {
        # Si c'est un asset dans build/, on le sert directement en enlevant /Laurelin/
        # Mais on garde /build/ dans l'URI finale
        rewrite ^/Laurelin/(.*)$ /$1 break;
        
        # On essaie d'abord de servir le fichier physique dans public/
        # Sinon, on passe la main à Laravel via index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Traitement des fichiers PHP
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
    }
}
